# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GameWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
import random

from PyQt5 import QtCore, QtGui, QtWidgets

from Colours import Colours


class Ui_GameWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1001, 900)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.field_widget = QtWidgets.QWidget(self.centralwidget)
        self.field_widget.setGeometry(QtCore.QRect(200, 0, 801, 800))
        self.field_widget.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.field_widget.setObjectName("field_widget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 10, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.turns_label = QtWidgets.QLabel(self.centralwidget)
        self.turns_label.setGeometry(QtCore.QRect(140, 10, 51, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.turns_label.setFont(font)
        self.turns_label.setObjectName("turns_label")
        self.restart_button = QtWidgets.QPushButton(self.centralwidget)
        self.restart_button.setGeometry(QtCore.QRect(30, 60, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.restart_button.setFont(font)
        self.restart_button.setObjectName("restart_button")
        self.colours_widget = QtWidgets.QWidget(self.centralwidget)
        self.colours_widget.setGeometry(QtCore.QRect(0, 800, 1900, 100))
        self.colours_widget.setObjectName("colours_widget")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.colours_widget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(-1, -1, 901, 101))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.menu_button = QtWidgets.QPushButton(self.centralwidget)
        self.menu_button.setGeometry(QtCore.QRect(40, 120, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.menu_button.setFont(font)
        self.menu_button.setObjectName("menu_button")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Прекраска"))
        self.label.setText(_translate("MainWindow", "Кол-во ходов:"))
        self.turns_label.setText(_translate("MainWindow", "0"))
        self.restart_button.setText(_translate("MainWindow", "Перезапуск"))
        self.menu_button.setText(_translate("MainWindow", "Меню"))
