# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(511, 575)
        MainWindow.setUnifiedTitleAndToolBarOnMac(True)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("")
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(100, 60, 311, 131))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(28)
        font.setBold(True)
        font.setWeight(75)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.playButton = QtWidgets.QPushButton(self.centralwidget)
        self.playButton.setGeometry(QtCore.QRect(180, 220, 131, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.playButton.setFont(font)
        self.playButton.setObjectName("playButton")
        self.parametersButton = QtWidgets.QPushButton(self.centralwidget)
        self.parametersButton.setGeometry(QtCore.QRect(180, 310, 131, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.parametersButton.setFont(font)
        self.parametersButton.setObjectName("parametersButton")
        self.rulesButton = QtWidgets.QPushButton(self.centralwidget)
        self.rulesButton.setGeometry(QtCore.QRect(180, 400, 131, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.rulesButton.setFont(font)
        self.rulesButton.setObjectName("rulesButton")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Перекраска"))
        self.label.setText(_translate("MainWindow", "Перекраска!"))
        self.playButton.setText(_translate("MainWindow", "Играть"))
        self.parametersButton.setText(_translate("MainWindow", "Настройки"))
        self.rulesButton.setText(_translate("MainWindow", "Правила"))
